const age = 17

if (age >= 18) {
    console.log('მომხმარებლის ასაკი არის 18 ან ზემოთ')
   } else {
       console.log('მომხმარებლის ასაკი არის 18-ზე ქვემოთ')
   }
   const weekDay = 7;
   
   switch (weekDay) {
   case 1:
   console.log("MONDAY")
     break;
     case 2:
     console.log("uesday")
     break;
     case 3:
    console.log("Wednesday")
    break;
  case 4:
      console.log("Thursday")
   break;
        case 5:
     console.log("Friday")
        break;
         case 6:
      console.log("Saturday")
              case 7:
      console.log("SUNDAY")
            break;
   }